# Generated by Django 3.2 on 2021-09-20 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тэга')),
                ('HEX_code', models.CharField(max_length=7, verbose_name='Цветовой код тэга')),
                ('slug', models.SlugField(verbose_name=' тэга')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(240), django.core.validators.MinValueValidator(1)], verbose_name='Время приготовленмя'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='content.Tag', verbose_name='Теги'),
        ),
    ]
