# Generated by Django 3.2 on 2021-09-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_favourite_shopping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(verbose_name='Тэг'),
        ),
    ]
