# Generated by Django 3.2 on 2021-09-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210924_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='HEX_code',
            new_name='color',
        ),
    ]
